# Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE file distributed with this work for additional information regarding copyright ownership. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.  

# This workflow will do a clean install of node dependencies, build the source code and run tests

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    env:
      COMPOSEUI_SKIP_DOWNLOAD: 'true'
      DOTNET_CONSOLE_ANSI_COLOR: 'true'
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        node-version: [ '18.x' ]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: ${{ matrix.node-version }}
        COMPOSEUI_SKIP_DOWNLOAD: ${{env.COMPOSEUI_SKIP_DOWNLOAD}}

    - name: Install NPM dependencies
      run: npm ci

    - name: Build JavaScript
      run: npx lerna run build
    
    - name: Test JavaScript
      run: npx lerna run test

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install NuGet dependencies
      run: |
        $failedSolutions = @()
        
        Get-ChildItem -Recurse -Include *.sln `
        | ForEach-Object {
            dotnet restore $_;
            if ($LASTEXITCODE -ne 0) {$failedSolutions += Split-Path $_ -leaf; }
          }
        
        if ($failedSolutions.count -gt 0) {
            throw "Restore FAILED for solutions $failedSolutions"
        }


    - name: Build .NET
      run: |
        $failedSolutions = @()
        
        Get-ChildItem -Recurse -Include *.sln `
        | ForEach-Object {
            dotnet build $_ --configuration Release --no-restore; 
            if ($LASTEXITCODE -ne 0) {$failedSolutions += Split-Path $_ -leaf; }
          }
        
        if ($failedSolutions.count -gt 0) {
            throw "Build FAILED for solutions $failedSolutions"
        }


    - name: Test .NET
      run: |
        $failedSolutions = @()
        
        Get-ChildItem -Recurse -Include *.sln `
        | ForEach-Object {
            dotnet test $_ --configuration Release --no-build; 
            if ($LASTEXITCODE -ne 0) { $failedSolutions += Split-Path $_ -leaf; }
        }
        
        if ($failedSolutions.count -gt 0) {
            throw "Test FAILED for solutions $failedSolutions"
        }


    - name: Codecov
      uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # By uploading it's shared with the other workflows that are reusing this
    - name: Upload Shell Binaries
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: shell-binaries
        path: ${{ github.workspace }}/src/shell/dotnet/Shell/bin/Release/net6.0-windows/
