on:
  release:
    types: [ published ]
    branches: [ main ]

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

name: Release

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  deploy_to_nuget:
    name: Publish messaging packages to nuget.org
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
        name: packages
        path: ./packages
      - uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: 6.0.x
      - name: Publish Messaging
        working-directory: ./packages
        run: |
             dir

